version: '3.7'

services:
  db:
    image: postgres
    container_name: backend_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root123456
      - POSTGRES_DB=backend_db
    volumes:
      - pgdata:/data/postgres
    
  app:
    build: .
    container_name: backend
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links: 
      - db
    depends_on:
      - db

volumes:
    pgdata: 
        driver: local
    
